@preconcurrency import AVFoundation
import OpusKit
import OpusShims
import OpusTypes
import XCTest

@MainActor
final class OpusCodecTests: XCTestCase {
    func testInit() throws {
        try AVAudioFormatTests.validFormats.forEach {
            _ = try Opus.Decoder(format: $0)
        }

        try AVAudioFormatTests.invalidFormats.forEach {
            XCTAssertThrowsError(try Opus.Decoder(format: $0)) { error in
                XCTAssertEqual(error as! Opus.Error, Opus.Error.badArgument)
            }
        }
    }

    func testCorruptedOpusDataThrowsInvalidPacketError() throws {
        guard let opusFormat = AVAudioFormat(opusPCMFormat: .int16, sampleRate: .hz16k, channels: .mono) else {
            XCTFail("Unable to generate desired opusFormat")
            return
        }

        let opusDecoder = try Opus.Decoder(format: opusFormat)
        // A corrupted, 40 bytes opus package, generated by a buggy Bluetooth piece of software. Other scenarios may
        // also be the cause of a similar issue.
        let corruptedOpusData = Data([
            191,
            232,
            174,
            215,
            224,
            130,
            236,
            126,
            177,
            204,
            165,
            85,
            230,
            201,
            43,
            16,
            207,
            120,
            223,
            247,
            59,
            117,
            41,
            235,
            55,
            96,
            78,
            68,
            7,
            207,
            184,
            255,
            254,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ])

        XCTAssertThrowsError(try opusDecoder.decode(corruptedOpusData)) { error in
            guard let opusError = error as? Opus.Error else {
                XCTFail("Unable to cast error to Opus.Error")
                return
            }

            XCTAssertEqual(opusError, Opus.Error.invalidPacket)
        }
    }

    func testEncodeDecodeRoundtrip() throws {
        let cfg = Opus.Config.voiceLowBW
        let enc = try Opus.Encoder(cfg)
        let dec = try Opus.Decoder(sampleRate: cfg.sampleRate, channels: cfg.channels)

        // 20 ms 440 Hz mono tone @16 kHz
        let frame = cfg.sampleRate.frameSize(.ms20)
        var pcm = [opus_int16](repeating: 0, count: Int(frame))
        for i in 0 ..< Int(frame) {
            let t = Double(i) / Double(cfg.sampleRate.rawValue)
            pcm[i] = opus_int16(3000.0 * sin(2.0 * .pi * 440.0 * t))
        }
        // Encode
        let pkt = try pcm.withUnsafeBufferPointer { ptr in
            try enc.encodePCM16(ptr.baseAddress!, sampleRate: cfg.sampleRate, duration: .ms20)
        }
        XCTAssertGreaterThan(pkt.count, 0)

        // Decode
        let out = try dec.decodePCM16(data: pkt, expected: .ms20)
        XCTAssertEqual(out.count, Int(frame)) // mono
    }

    // MARK: - Encoder Tests

    func testEncoderInit() throws {
        try AVAudioFormatTests.validFormats.forEach {
            _ = try Opus.Encoder(format: $0)
        }

        try AVAudioFormatTests.invalidFormats.forEach {
            XCTAssertThrowsError(try Opus.Encoder(format: $0)) { error in
                XCTAssertEqual(error as! Opus.Error, Opus.Error.badArgument)
            }
        }
    }
}
